project_name: go-health-check
release:
  github:
    owner: UnAfraid
    name: go-health-check
  name_template: '{{.Tag}}'
builds:
  -
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
     - windows
     - linux
     - darwin
    goarch:
     - amd64
     - 386
     - arm
    goarm:
     - 6
     - 7
